import type { BerryProject } from '@/lib/project/types'
import { buildProjectPinMap } from './pin-map'
import type { CodegenResult, MappedLed } from './types'

/**
 * Convert a component id into a safe C++ identifier suffix.
 * @param componentId Project component instance id.
 */
function toIdentifierSuffix(componentId: string): string {
  return componentId.replace(/[^a-zA-Z0-9_]/g, '_').toUpperCase()
}

/**
 * Serial baud rate for generated board bring-up sketches.
 * @param board Target board profile id.
 */
function serialBaudRate(board: BerryProject['board']): number {
  return board === 'esp32-devkit-v1' ? 115200 : 9600
}

/**
 * Render one LED pin constant block for generated source.
 * @param led Mapped LED entry from the pin map.
 */
function renderLedConstant(led: MappedLed): string {
  const suffix = toIdentifierSuffix(led.componentId)
  return [
    `// ${led.componentName} (${led.componentId})`,
    `// ${led.gpio.boardTerminalLabel} (${led.gpio.boardTerminalId}) -> anode`,
    `constexpr int ${suffix}_PIN = ${led.gpio.arduinoPin};`,
  ].join('\n')
}

/**
 * Generate Arduino-framework firmware from the project wiring graph.
 * @param project Berry project graph.
 */
export function generateFirmwareFromProject(project: BerryProject): CodegenResult {
  const pinMap = buildProjectPinMap(project)
  const notes: string[] = []
  const baud = serialBaudRate(project.board)

  if (!pinMap.mcuComponentId) {
    notes.push('No MCU matching project.board was found on the bench.')
  }

  if (pinMap.leds.length === 0) {
    notes.push('No GPIO-driven LEDs were detected; generated a serial-ready skeleton sketch.')
  } else {
    notes.push(`Mapped ${pinMap.leds.length} LED${pinMap.leds.length === 1 ? '' : 's'} from wiring graph.`)
  }

  const ledConstants = pinMap.leds.map(renderLedConstant).join('\n\n')
  const ledPinNames = pinMap.leds.map((led) => `${toIdentifierSuffix(led.componentId)}_PIN`)

  const setupLines = [
    `  Serial.begin(${baud});`,
    ...ledPinNames.map((pin) => `  pinMode(${pin}, OUTPUT);`),
  ]

  const loopLines =
    ledPinNames.length === 0
      ? ['  // Add loop logic after wiring more peripherals.', '  delay(1000);']
      : [
          ...ledPinNames.map((pin) => `  digitalWrite(${pin}, HIGH);`),
          '  delay(500);',
          ...ledPinNames.map((pin) => `  digitalWrite(${pin}, LOW);`),
          '  delay(500);',
        ]

  const source = [
    '// Generated by berry. from the Studio wiring graph.',
    '// Regenerate with toolbar Generate or edit manually below.',
    '#include <Arduino.h>',
    '',
    pinMap.leds.length > 0 ? '// Pin map\n' + ledConstants : '// Pin map\n// (none detected)',
    '',
    'void setup() {',
    ...setupLines,
    '}',
    '',
    'void loop() {',
    ...loopLines,
    '}',
    '',
  ].join('\n')

  return {
    ok: pinMap.mcuComponentId.length > 0,
    source,
    pinMap,
    notes,
  }
}
