import { describe, expect, it } from 'vitest'
import {
  createDefaultFirmwareSource,
  hasMeaningfulFirmwareSource,
  isDefaultFirmwareSource,
  isEmptyGeneratedFirmwareSource,
  shouldPreserveExistingFirmwareSource,
} from './source'

const hostedAgentSkeleton = `// Generated by berry. hosted agent.
#include <Arduino.h>

void setup() {
  Serial.begin(115200);
}

void loop() {
  delay(1000);
}
`

const idleSkeletonWithoutMarker = `#include <Arduino.h>

void setup() {
  Serial.begin(115200);
}

void loop() {
  delay(1000);
}
`

const meaningfulFirmware = `#include <Arduino.h>

const int LED_PIN = 13;

void setup() {
  pinMode(LED_PIN, OUTPUT);
}

void loop() {
  digitalWrite(LED_PIN, HIGH);
  delay(500);
  digitalWrite(LED_PIN, LOW);
  delay(500);
}
`

const generatedMeaningfulFirmware = `// Generated by berry. from the Studio wiring graph.
#include <Arduino.h>

constexpr int LED_1_PIN = 13;

void setup() {
  Serial.begin(115200);
  pinMode(LED_1_PIN, OUTPUT);
}

void loop() {
  digitalWrite(LED_1_PIN, HIGH);
  delay(500);
  digitalWrite(LED_1_PIN, LOW);
  delay(500);
}
`

describe('firmware source preservation', () => {
  it('classifies board starter firmware as default and not meaningful', () => {
    const source = createDefaultFirmwareSource('esp32-devkit-v1')

    expect(isDefaultFirmwareSource(source)).toBe(true)
    expect(isEmptyGeneratedFirmwareSource(source)).toBe(true)
    expect(hasMeaningfulFirmwareSource(source)).toBe(false)
  })

  it('classifies hosted-agent skeleton firmware as empty source', () => {
    expect(isEmptyGeneratedFirmwareSource(hostedAgentSkeleton)).toBe(true)
    expect(hasMeaningfulFirmwareSource(hostedAgentSkeleton)).toBe(false)
  })

  it('classifies idle skeleton firmware without a generated marker as empty source', () => {
    expect(isDefaultFirmwareSource(idleSkeletonWithoutMarker)).toBe(true)
    expect(isEmptyGeneratedFirmwareSource(idleSkeletonWithoutMarker)).toBe(true)
    expect(hasMeaningfulFirmwareSource(idleSkeletonWithoutMarker)).toBe(false)
  })

  it('does not treat generated firmware with real behavior as empty source', () => {
    expect(isEmptyGeneratedFirmwareSource(generatedMeaningfulFirmware)).toBe(false)
    expect(hasMeaningfulFirmwareSource(generatedMeaningfulFirmware)).toBe(true)
  })

  it('preserves meaningful firmware when an empty generated sketch is returned', () => {
    expect(
      shouldPreserveExistingFirmwareSource(meaningfulFirmware, hostedAgentSkeleton),
    ).toBe(true)
  })

  it('allows generated starter firmware to be replaced by meaningful firmware', () => {
    expect(
      shouldPreserveExistingFirmwareSource(hostedAgentSkeleton, meaningfulFirmware),
    ).toBe(false)
  })

  it('allows meaningful firmware to be replaced by different meaningful firmware', () => {
    const nextMeaningfulFirmware = meaningfulFirmware.replace('LED_PIN = 13', 'LED_PIN = 12')

    expect(
      shouldPreserveExistingFirmwareSource(meaningfulFirmware, nextMeaningfulFirmware),
    ).toBe(false)
  })
})
